version: '3.8'

services:
  media-mcp:
    build: .
    container_name: media-mcp
    restart: always
    ports:
      - '3010:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./.cookie:/app/.cookie
